// <auto-generated />
using System;
using AuthWebApi.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthWebApi.Migrations.MysqlDb
{
    [DbContext(typeof(MysqlDbContext))]
    partial class MysqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("DataModelLayer.Models.Comments.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("Likes");

                    b.Property<string>("Message");

                    b.Property<int>("PostId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DataModelLayer.Models.Comments.CommentFiles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CommentId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("Comment_Files");
                });

            modelBuilder.Entity("DataModelLayer.Models.Comments.CommentLike", b =>
                {
                    b.Property<long>("LikeId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CommentId");

                    b.Property<int>("LikeCount");

                    b.Property<DateTime>("LikeTime");

                    b.Property<string>("UserId");

                    b.HasKey("LikeId");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentLikes");
                });

            modelBuilder.Entity("DataModelLayer.Models.Entities.UserCommonData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("FacebookId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("UserEmail");

                    b.Property<string>("UserId");

                    b.Property<int>("UserLevel");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("UserCommonData");
                });

            modelBuilder.Entity("DataModelLayer.Models.Posts.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<int>("Likes");

                    b.Property<string>("PostTtile");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("DataModelLayer.Models.Posts.PostFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PostId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostFiles");
                });

            modelBuilder.Entity("DataModelLayer.Models.Posts.PostLike", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LikeCount");

                    b.Property<DateTime>("LikeTime");

                    b.Property<int>("PostId");

                    b.Property<string>("UserId");

                    b.HasKey("LikeId");

                    b.ToTable("PostLikes");
                });

            modelBuilder.Entity("DataModelLayer.Models.Tikets.ReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressedById");

                    b.Property<string>("AddressedMessage");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EntityId");

                    b.Property<bool>("IsAddressed");

                    b.Property<string>("Message");

                    b.Property<string>("ReportedByUserId");

                    b.Property<int>("ReportedEntityId");

                    b.HasKey("Id");

                    b.ToTable("ReportEntity");
                });

            modelBuilder.Entity("DataModelLayer.Models.Tikets.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressedById");

                    b.Property<string>("AddressedMessage");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsAddressed");

                    b.Property<bool>("IsPending");

                    b.Property<string>("Message");

                    b.Property<string>("TicketIssuerUserId");

                    b.HasKey("Id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("DataModelLayer.Models.Posts.PostFiles", b =>
                {
                    b.HasOne("DataModelLayer.Models.Posts.Post")
                        .WithMany("Files")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
